# Generated by Django 6.0.7 on 2026-07-20 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("recipe_id", models.CharField(db_index=True, max_length=40, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                ("lang", models.CharField(default="en", max_length=16)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("unlisted", "Unlisted"),
                            ("public", "Public"),
                        ],
                        db_index=True,
                        default="private",
                        max_length=16,
                    ),
                ),
                ("license_spdx", models.CharField(blank=True, default="", max_length=64)),
                ("source_url", models.URLField(blank=True, default="")),
                ("tags", models.JSONField(default=list)),
                ("head_version_id", models.CharField(db_index=True, max_length=72)),
                ("head_content_hash", models.CharField(max_length=72)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(db_index=True)),
                ("indexed_at", models.DateTimeField(auto_now=True)),
                (
                    "forked_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="catalog.recipe",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RecipeVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version_id", models.CharField(db_index=True, max_length=72, unique=True)),
                ("content_hash", models.CharField(db_index=True, max_length=72)),
                ("parents", models.JSONField(default=list)),
                ("origin", models.CharField(max_length=24)),
                ("author_key", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(db_index=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="catalog.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
            },
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["owner", "visibility"], name="catalog_rec_owner_i_88b7f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["visibility", "-updated_at"], name="catalog_rec_visibil_36a1e2_idx"
            ),
        ),
    ]
